version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: test_db
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      -  ./data:/var/lib/mysql
volumes:
  my-db: