version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      -  ./data:/var/lib/postgresql/data 